site_name: django-statusboard-notify
site_description: Utility for [django-statusboard][1] that notifies users about service status changes.
site_author: Emanuele Di Giacomo <emanuele@digiacomo.cc>
copyright: Copyright (C) 2021 Emanuele Di Giacomo <emanuele@digiacomo.cc>
repo_url: https://github.com/edigiacomo/django-statusboard-notify
nav:
    - Home: index.md

theme: readthedocs
