name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Python ${{ matrix.python }} - Django ${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - django: 32
            python: "3.8"
          - django: 32
            python: "3.9"
          - django: 32
            python: "3.10"
          - django: 42
            python: "3.8"
          - django: 42
            python: "3.9"
          - django: 42
            python: "3.10"
          - django: 42
            python: "3.11"
          - django: 42
            python: "3.12"
          - django: 52
            python: "3.10"
          - django: 52
            python: "3.11"
          - django: 52
            python: "3.12"
          - django: 52
            python: "3.13"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Update packaging tools
        run: python -m pip install --upgrade pip setuptools virtualenv wheel
      - name: Install dependencies
        run: |
          sudo apt install -y pandoc
          python -m pip install --upgrade tox
      - name: Run tests
        run: tox -e py$(echo ${{ matrix.python-version }} | tr -d .)-django${{ matrix.django }}
      - name: Run codecov
        uses: codecov/codecov-action@v3
        if: matrix.python == '3.11' && matrix.django == '42'
