name: Build
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    name: Python ${{ matrix.python }} - Django ${{ matrix.django }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
        django: [32, 41]
        exclude:
          - python: "3.6"
            django: 41
    steps:
      - name: Install system dependencies
        run: |
          sudo apt install -y pandoc
          pip install tox tox-travis flake8 codecov
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run tests
        run: tox -e py-django${{ matrix.django }}
      - name: Run codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
