name: Docs
on:
  push:
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: pip install tox
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Run mkdocs
        run: tox -e docs
